export const TODO_LIST_REQUEST='TODO_LIST_REQUEST'
export const TODO_LIST_SUCCESS='TODO_LIST_SUCCESS'
export const TODO_LIST_FAIL='TODO_LIST_FAIL'

export const TODO_DETAIL_REQUEST='TODO_DETAIL_REQUEST'
export const TODO_DETAIL_SUCCESS='TODO_DETAIL_SUCCESS'
export const TODO_DETAIL_FAIL='TODO_DETAIL_FAIL'

export const TODO_DELETE_REQUEST='TODO_DELETE_REQUEST'
export const TODO_DELETE_SUCCESS='TODO_DELETE_SUCCESS'
export const TODO_DELETE_FAIL='TODO_DELETE_FAIL'

export const TODO_UPDATE_REQUEST = 'TODO_UPDATE_REQUEST'
export const TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS'
export const TODO_UPDATE_FAIL = 'TODO_UPDATE_FAIL'

export const TODO_CREATE_REQUEST = 'TODO_CREATE_REQUEST'
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS'
export const TODO_CREATE_FAIL = 'TODO_CREATE_FAIL'
